/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CommsToDTC: typeof import('./src/components/DTCExports/commsToDTC.vue')['default']
    EditHistory: typeof import('./src/components/history/editHistory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFlight: typeof import('./src/components/PackageFlightSelection/SelectFlight.vue')['default']
    SteerpointsToDTC: typeof import('./src/components/DTCExports/steerpointsToDTC.vue')['default']
    ZDiagram: typeof import('./src/components/z-diagram/z-diagram.vue')['default']
  }
}
